Repository PomeTeam/POME_Server, pull requests merged in 2023-01, with the labels that each got.

#73 [feature/goal category service] 목표 및 목표 카테고리 CRUD 기능 개발
  src/main/java/com/example/pomeserver/domain/goal/controller/GoalCategoryController.java
  src/main/java/com/example/pomeserver/domain/goal/controller/GoalController.java
  src/main/java/com/example/pomeserver/domain/goal/dto/assembler/GoalAssembler.java
  src/main/java/com/example/pomeserver/domain/goal/dto/assembler/GoalCategoryAssembler.java
  src/main/java/com/example/pomeserver/domain/goal/dto/request/GoalCategoryCreateRequest.java
  src/main/java/com/example/pomeserver/domain/goal/entity/Goal.java
  src/main/java/com/example/pomeserver/domain/goal/entity/GoalCategory.java
  src/main/java/com/example/pomeserver/domain/goal/exception/GoalExceptionList.java
  src/main/java/com/example/pomeserver/domain/goal/exception/excute/GoalCategoryDuplicationException.java
  src/main/java/com/example/pomeserver/domain/goal/exception/excute/GoalCategoryListSizeException.java
  src/main/java/com/example/pomeserver/domain/goal/repository/GoalCategoryRepository.java
  src/main/java/com/example/pomeserver/domain/goal/repository/GoalRepository.java
  src/main/java/com/example/pomeserver/domain/goal/service/GoalCategoryService.java
  src/main/java/com/example/pomeserver/domain/goal/service/GoalCategoryServiceImpl.java
  src/main/java/com/example/pomeserver/domain/goal/service/GoalService.java
  src/main/java/com/example/pomeserver/domain/goal/service/GoalServiceImpl.java
  src/main/java/com/example/pomeserver/domain/user/entity/User.java
Labels: implement

#83 #82 FriendSearchResponse 응답 객체에 friendUserId 추가
  src/main/java/com/example/pomeserver/domain/user/dto/response/FriendSearchResponse.java
  src/main/java/com/example/pomeserver/domain/user/service/UserServiceImpl.java
Labels: dtoEdit

#84 #82 GoalResponse에 nickname 추가
  src/main/java/com/example/pomeserver/domain/goal/dto/response/GoalResponse.java
Labels: dtoEdit

#85 #82 #45 RecordResponse에 oneLineMind 추가 + User로 조건으로 기록 조회 API 추가
  src/main/java/com/example/pomeserver/domain/record/controller/RecordController.java
  src/main/java/com/example/pomeserver/domain/record/dto/response/RecordResponse.java
  src/main/java/com/example/pomeserver/domain/record/repository/RecordRepository.java
  src/main/java/com/example/pomeserver/domain/record/repository/RecordRepositoryCustom.java
  src/main/java/com/example/pomeserver/domain/record/repository/RecordRepositoryCustomImpl.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordService.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordServiceImpl.java
Labels: implement, dtoEdit

#87 #45 친구들의 기록 불러오기 api 추가
  src/main/java/com/example/pomeserver/domain/record/controller/RecordController.java
  src/main/java/com/example/pomeserver/domain/record/repository/RecordRepositoryCustom.java
  src/main/java/com/example/pomeserver/domain/record/repository/RecordRepositoryCustomImpl.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordService.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordServiceImpl.java
  src/main/java/com/example/pomeserver/domain/user/repository/FollowRepository.java
Labels: implement

#88 #82 Goal 생성 시, goalCategoryId에서 Name으로 변경
  src/main/java/com/example/pomeserver/domain/goal/dto/assembler/GoalCategoryAssembler.java
  src/main/java/com/example/pomeserver/domain/goal/dto/request/GoalCreateRequest.java
  src/main/java/com/example/pomeserver/domain/goal/repository/GoalCategoryRepository.java
  src/main/java/com/example/pomeserver/domain/goal/service/GoalCategoryServiceImpl.java
  src/main/java/com/example/pomeserver/domain/goal/service/GoalServiceImpl.java
Labels: dtoEdit

#89 #82 목표response 수정 | #45 친구 불러오기 api 추가
  src/main/java/com/example/pomeserver/domain/goal/dto/assembler/GoalCategoryAssembler.java
  src/main/java/com/example/pomeserver/domain/goal/dto/request/GoalCreateRequest.java
  src/main/java/com/example/pomeserver/domain/goal/repository/GoalCategoryRepository.java
  src/main/java/com/example/pomeserver/domain/goal/service/GoalCategoryServiceImpl.java
  src/main/java/com/example/pomeserver/domain/goal/service/GoalServiceImpl.java
  src/main/java/com/example/pomeserver/domain/record/controller/RecordController.java
  src/main/java/com/example/pomeserver/domain/record/repository/RecordRepositoryCustom.java
  src/main/java/com/example/pomeserver/domain/record/repository/RecordRepositoryCustomImpl.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordService.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordServiceImpl.java
  src/main/java/com/example/pomeserver/domain/user/repository/FollowRepository.java
Labels: implement

#90 Feature/record service
  src/main/java/com/example/pomeserver/domain/record/controller/RecordController.java
  src/main/java/com/example/pomeserver/domain/record/dto/response/emotion/EmotionResponse.java
  src/main/java/com/example/pomeserver/domain/record/dto/response/emotion/MyEmotionResponse.java
  src/main/java/com/example/pomeserver/domain/record/dto/response/record/MyRecordResponse.java
  src/main/java/com/example/pomeserver/domain/record/dto/response/record/RecordResponse.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordService.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordServiceImpl.java
Labels: implement, dtoEdit

#91 Hotfix/user nickname 유저 닉네임 중복 체크 오류 해결
  src/main/java/com/example/pomeserver/domain/user/service/UserServiceImpl.java
Labels: implement, hotfix

#92 main <- develop
  src/main/java/com/example/pomeserver/domain/record/controller/RecordController.java
  src/main/java/com/example/pomeserver/domain/record/dto/response/emotion/EmotionResponse.java
  src/main/java/com/example/pomeserver/domain/record/dto/response/emotion/MyEmotionResponse.java
  src/main/java/com/example/pomeserver/domain/record/dto/response/record/MyRecordResponse.java
  src/main/java/com/example/pomeserver/domain/record/dto/response/record/RecordResponse.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordService.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordServiceImpl.java
  src/main/java/com/example/pomeserver/domain/user/service/UserServiceImpl.java
Labels: deploy

#94 hotfix/user-check 유저 확인 기능 구현
  src/main/java/com/example/pomeserver/domain/user/controller/UserController.java
  src/main/java/com/example/pomeserver/domain/user/dto/request/UserSignUpRequest.java
  src/main/java/com/example/pomeserver/domain/user/service/UserService.java
  src/main/java/com/example/pomeserver/domain/user/service/UserServiceImpl.java
Labels: hotfix

#95 #82 record 응답 객체에 createdAt 추가
  src/main/java/com/example/pomeserver/domain/record/dto/response/record/MyRecordResponse.java
  src/main/java/com/example/pomeserver/domain/record/dto/response/record/RecordResponse.java
Labels: dtoEdit

#103 #102 목표 생성 및 수정, 목표 카테고리 생성 시 유효성 검사 어노테이션 추가
  src/main/java/com/example/pomeserver/domain/goal/controller/GoalCategoryController.java
  src/main/java/com/example/pomeserver/domain/goal/controller/GoalController.java
Labels: hotfix

#113 45 #82 emotion 응답에 감정을 남긴 사용자의 nickname 추가(FriendEmotion)
  src/main/java/com/example/pomeserver/domain/record/dto/response/emotion/EmotionResponse.java
  src/main/java/com/example/pomeserver/domain/record/dto/response/emotion/FriendEmotion.java
  src/main/java/com/example/pomeserver/domain/record/dto/response/emotion/MyEmotionResponse.java
Labels: implement, dtoEdit

#114 45 #82 record, emotion 응답 객체에 @ApiModel 어노테이션 주석 처리
  src/main/java/com/example/pomeserver/domain/record/dto/response/emotion/EmotionResponse.java
  src/main/java/com/example/pomeserver/domain/record/dto/response/emotion/FriendEmotion.java
  src/main/java/com/example/pomeserver/domain/record/dto/response/emotion/MyEmotionResponse.java
  src/main/java/com/example/pomeserver/domain/record/dto/response/record/MyRecordResponse.java
  src/main/java/com/example/pomeserver/domain/record/dto/response/record/RecordResponse.java
Labels: dtoEdit

#116 45 #82 record, emotion 응답 객체의 @ApiModelProperty의 datatype 제거 <-- 적용되지…
  src/main/java/com/example/pomeserver/domain/record/dto/response/emotion/EmotionResponse.java
  src/main/java/com/example/pomeserver/domain/record/dto/response/emotion/FriendEmotion.java
  src/main/java/com/example/pomeserver/domain/record/dto/response/emotion/MyEmotionResponse.java
  src/main/java/com/example/pomeserver/domain/record/dto/response/record/MyRecordResponse.java
  src/main/java/com/example/pomeserver/domain/record/dto/response/record/RecordResponse.java
Labels: dtoEdit
