Repository PomeTeam/POME_Server, pull requests merged in 2023-03, with the labels that each got.

#206 #40 (QA반영) 유저 닉네임 에러 메시지 변경
  src/main/java/com/example/pomeserver/domain/user/dto/request/UserNicknameRequest.java
  src/main/java/com/example/pomeserver/domain/user/exception/UserExceptionList.java
Labels: refactor

#207 main <- develop
  src/main/java/com/example/pomeserver/domain/user/dto/request/UserNicknameRequest.java
  src/main/java/com/example/pomeserver/domain/user/exception/UserExceptionList.java
Labels: refactor

#209 #208 기록 생성 (성공) 테스트 코드 작성
  src/main/java/com/example/pomeserver/domain/record/dto/request/RecordCreateRequest.java
  src/main/java/com/example/pomeserver/domain/record/dto/response/record/RecordResponse.java
  src/main/java/com/example/pomeserver/domain/record/entity/Emotion.java
  src/main/java/com/example/pomeserver/global/entity/DateBaseEntity.java
  src/test/java/com/example/pomeserver/domain/record/service/RecordTest.java
Labels: testCode

#210 Feature/record service
  src/main/java/com/example/pomeserver/domain/record/dto/assembler/RecordAssembler.java
  src/main/java/com/example/pomeserver/domain/record/dto/request/RecordUpdateRequest.java
  src/test/java/com/example/pomeserver/domain/record/service/RecordTest.java
Labels: testCode

#211 main <- dev
  src/main/java/com/example/pomeserver/domain/record/dto/assembler/RecordAssembler.java
  src/main/java/com/example/pomeserver/domain/record/dto/request/RecordCreateRequest.java
  src/main/java/com/example/pomeserver/domain/record/dto/request/RecordUpdateRequest.java
  src/main/java/com/example/pomeserver/domain/record/dto/response/record/RecordResponse.java
  src/main/java/com/example/pomeserver/domain/record/entity/Emotion.java
  src/main/java/com/example/pomeserver/global/entity/DateBaseEntity.java
  src/test/java/com/example/pomeserver/domain/record/service/RecordTest.java
Labels: deploy

#213 #212 탈퇴한 회원 재가입 로직 구성
  src/main/java/com/example/pomeserver/domain/user/entity/User.java
  src/main/java/com/example/pomeserver/domain/user/service/UserServiceImpl.java
  src/test/java/com/example/pomeserver/domain/user/controller/UserControllerTest.java
  src/test/java/com/example/pomeserver/domain/user/service/UserServiceTest.java
Labels: refactor

#216 main <- dev
  src/main/java/com/example/pomeserver/domain/record/service/RecordServiceImpl.java
  src/test/java/com/example/pomeserver/domain/record/service/RecordTest.java
Labels: deploy

#217 #40 문자 전송 번호 일정 응답값
  src/main/java/com/example/pomeserver/global/util/sms/service/SmsServiceImpl.java
Labels: refactor

#218 main <- develop
  src/main/java/com/example/pomeserver/global/util/sms/service/SmsServiceImpl.java
Labels: refactor

#219 #40 문자 전송 번호 랜덤 응답값
  src/main/java/com/example/pomeserver/global/util/sms/service/SmsServiceImpl.java
Labels: pre-pass

#220 main <- develop
  src/main/java/com/example/pomeserver/global/util/sms/service/SmsServiceImpl.java
Labels: pre-pass
