Repository PomeTeam/POME_Server, pull requests merged in 2023-02, with the labels that each got.

#118 #82 #45 기록에 감정 남기기가 적용되지 않는 버그 해결+MyEmotionResponse에 friendEmotions 배…
  src/main/java/com/example/pomeserver/domain/record/controller/RecordController.java
  src/main/java/com/example/pomeserver/domain/record/dto/response/emotion/EmotionResponse.java
  src/main/java/com/example/pomeserver/domain/record/dto/response/emotion/MyEmotionResponse.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordService.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordServiceImpl.java
Labels: implement, dtoEdit

#119 main <-- deploy
  src/main/java/com/example/pomeserver/domain/record/controller/RecordController.java
  src/main/java/com/example/pomeserver/domain/record/dto/response/emotion/EmotionResponse.java
  src/main/java/com/example/pomeserver/domain/record/dto/response/emotion/MyEmotionResponse.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordService.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordServiceImpl.java
Labels: deploy

#120 #82 #45 MyEmotionResponse-->EmotionResponse로 통합 + 본인의 기록에 남긴 MyEmotio…
  src/main/java/com/example/pomeserver/domain/record/controller/RecordController.java
  src/main/java/com/example/pomeserver/domain/record/dto/response/emotion/EmotionResponse.java
  src/main/java/com/example/pomeserver/domain/record/dto/response/emotion/MyEmotionResponse.java
  src/main/java/com/example/pomeserver/domain/record/dto/response/record/MyRecordResponse.java
  src/main/java/com/example/pomeserver/domain/record/entity/vo/EmotionType.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordService.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordServiceImpl.java
Labels: implement, dtoEdit

#121 main <- dev
  src/main/java/com/example/pomeserver/domain/record/controller/RecordController.java
  src/main/java/com/example/pomeserver/domain/record/dto/response/emotion/EmotionResponse.java
  src/main/java/com/example/pomeserver/domain/record/dto/response/emotion/MyEmotionResponse.java
  src/main/java/com/example/pomeserver/domain/record/dto/response/record/MyRecordResponse.java
  src/main/java/com/example/pomeserver/domain/record/entity/vo/EmotionType.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordService.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordServiceImpl.java
Labels: deploy

#124 #82 #45 친구의 기록에 감정 남기기: 이미 감정을 남긴 경우 누적이 아닌 수정될 수 있도록 적용
  src/main/java/com/example/pomeserver/domain/record/entity/EmotionRecord.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordServiceImpl.java
Labels: implement, dtoEdit

#123 #122 #40 이미지키값을 URL로 Response반영
  src/main/java/com/example/pomeserver/domain/user/dto/response/FriendSearchResponse.java
  src/main/java/com/example/pomeserver/domain/user/dto/response/UserResponse.java
  src/main/java/com/example/pomeserver/domain/user/service/UserServiceImpl.java
  src/main/java/com/example/pomeserver/global/util/aws/s3/ImageService.java
  src/main/java/com/example/pomeserver/global/util/redis/template/RedisTemplateService.java
  src/main/resources/application.yml
Labels: implement

#125 main <- dev
  src/main/java/com/example/pomeserver/domain/record/entity/EmotionRecord.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordServiceImpl.java
  src/main/java/com/example/pomeserver/domain/user/dto/response/FriendSearchResponse.java
  src/main/java/com/example/pomeserver/domain/user/dto/response/UserResponse.java
  src/main/java/com/example/pomeserver/domain/user/service/UserServiceImpl.java
  src/main/java/com/example/pomeserver/global/util/aws/s3/ImageService.java
  src/main/java/com/example/pomeserver/global/util/redis/template/RedisTemplateService.java
  src/main/resources/application.yml
Labels: deploy

#127 [feature/goal service] 목표 종료하기 API 기능 개발
  src/main/java/com/example/pomeserver/domain/goal/controller/GoalController.java
  src/main/java/com/example/pomeserver/domain/goal/dto/request/GoalTerminateRequest.java
  src/main/java/com/example/pomeserver/domain/goal/dto/response/GoalResponse.java
  src/main/java/com/example/pomeserver/domain/goal/entity/Goal.java
  src/main/java/com/example/pomeserver/domain/goal/exception/GoalExceptionList.java
  src/main/java/com/example/pomeserver/domain/goal/exception/excute/GoalAlreadyEndException.java
  src/main/java/com/example/pomeserver/domain/goal/exception/excute/GoalCanNotEndException.java
  src/main/java/com/example/pomeserver/domain/goal/repository/GoalRepository.java
  src/main/java/com/example/pomeserver/domain/goal/service/GoalService.java
  src/main/java/com/example/pomeserver/domain/goal/service/GoalServiceImpl.java
  src/main/java/com/example/pomeserver/domain/record/controller/RecordController.java
Labels: implement

#128 Feature/record service
  src/main/java/com/example/pomeserver/domain/goal/service/GoalServiceImpl.java
  src/main/java/com/example/pomeserver/domain/record/controller/RecordController.java
  src/main/java/com/example/pomeserver/domain/record/dto/assembler/RecordAssembler.java
  src/main/java/com/example/pomeserver/domain/record/dto/response/emotion/EmotionResponse.java
  src/main/java/com/example/pomeserver/domain/record/dto/response/record/RecordResponse.java
  src/main/java/com/example/pomeserver/domain/record/entity/EmotionRecord.java
  src/main/java/com/example/pomeserver/domain/record/entity/Record.java
  src/main/java/com/example/pomeserver/domain/record/repository/RecordRepository.java
  src/main/java/com/example/pomeserver/domain/record/repository/RecordRepositoryCustom.java
  src/main/java/com/example/pomeserver/domain/record/repository/RecordRepositoryCustomImpl.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordService.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordServiceImpl.java
Labels: implement

#130 [feature/goal service] 목표 조회 시, 사용금액 계산 로직 수정
  src/main/java/com/example/pomeserver/domain/goal/dto/response/GoalResponse.java
  src/main/java/com/example/pomeserver/domain/goal/entity/Goal.java
  src/main/java/com/example/pomeserver/domain/goal/service/GoalServiceImpl.java
Labels: dtoEdit

#129 main <- dev
  src/main/java/com/example/pomeserver/domain/goal/controller/GoalController.java
  src/main/java/com/example/pomeserver/domain/goal/dto/request/GoalTerminateRequest.java
  src/main/java/com/example/pomeserver/domain/goal/dto/response/GoalResponse.java
  src/main/java/com/example/pomeserver/domain/goal/entity/Goal.java
  src/main/java/com/example/pomeserver/domain/goal/exception/GoalExceptionList.java
  src/main/java/com/example/pomeserver/domain/goal/exception/excute/GoalAlreadyEndException.java
  src/main/java/com/example/pomeserver/domain/goal/exception/excute/GoalCanNotEndException.java
  src/main/java/com/example/pomeserver/domain/goal/repository/GoalRepository.java
  src/main/java/com/example/pomeserver/domain/goal/service/GoalService.java
  src/main/java/com/example/pomeserver/domain/goal/service/GoalServiceImpl.java
  src/main/java/com/example/pomeserver/domain/record/controller/RecordController.java
  src/main/java/com/example/pomeserver/domain/record/dto/assembler/RecordAssembler.java
  src/main/java/com/example/pomeserver/domain/record/dto/response/emotion/EmotionResponse.java
  src/main/java/com/example/pomeserver/domain/record/dto/response/record/RecordResponse.java
  src/main/java/com/example/pomeserver/domain/record/entity/EmotionRecord.java
  src/main/java/com/example/pomeserver/domain/record/entity/Record.java
  src/main/java/com/example/pomeserver/domain/record/repository/RecordRepository.java
  src/main/java/com/example/pomeserver/domain/record/repository/RecordRepositoryCustom.java
  src/main/java/com/example/pomeserver/domain/record/repository/RecordRepositoryCustomImpl.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordService.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordServiceImpl.java
Labels: deploy

#132 [hotfix/goal-service] 목표 삭제 API 로직 수정
  src/main/java/com/example/pomeserver/domain/goal/service/GoalServiceImpl.java
Labels: hotfix

#134 main <- dev
  src/main/java/com/example/pomeserver/domain/goal/service/GoalServiceImpl.java
  src/main/java/com/example/pomeserver/domain/record/entity/Record.java
  src/main/java/com/example/pomeserver/domain/record/repository/RecordRepositoryCustomImpl.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordServiceImpl.java
Labels: deploy

#136 [hotfix/goal-service] 목표 생성 시, 유저가 가질 수 있는 목표 카테고리 개수 제한 조건 수정
  src/main/java/com/example/pomeserver/domain/goal/service/GoalServiceImpl.java
Labels: hotfix

#138 [infra/build-test] develop 브랜치의 CI 워크플로우에 테스트코드 레포팅 작업 추가
  .github/workflows/build-test-dev.yml
  .github/workflows/build-test-prod.yml
  src/test/java/com/example/pomeserver/domain/goal/service/GoalServiceImplTest.java
Labels: infra

#140 [infra/build-test] PROD CI 워크플로우 롤백
  .github/workflows/build-test-prod.yml
Labels: infra

#139 main <- develop
  .github/workflows/build-test-dev.yml
  src/main/java/com/example/pomeserver/domain/goal/service/GoalServiceImpl.java
  src/test/java/com/example/pomeserver/domain/goal/service/GoalServiceImplTest.java
Labels: deploy

#141 #45 record 조회 회고탭/ 기록탭 분리
  src/main/java/com/example/pomeserver/domain/record/controller/RecordController.java
  src/main/java/com/example/pomeserver/domain/record/repository/RecordRepositoryCustom.java
  src/main/java/com/example/pomeserver/domain/record/repository/RecordRepositoryCustomImpl.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordService.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordServiceImpl.java
Labels: implement

#142 main <- dev
  src/main/java/com/example/pomeserver/domain/record/controller/RecordController.java
  src/main/java/com/example/pomeserver/domain/record/repository/RecordRepositoryCustom.java
  src/main/java/com/example/pomeserver/domain/record/repository/RecordRepositoryCustomImpl.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordService.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordServiceImpl.java
Labels: deploy

#143 #45 기록탭 조회 일주일이 지난 기록은 응답으로 제외하도록 jpql 수정
  src/main/java/com/example/pomeserver/domain/record/controller/RecordController.java
  src/main/java/com/example/pomeserver/domain/record/repository/RecordRepositoryCustom.java
  src/main/java/com/example/pomeserver/domain/record/repository/RecordRepositoryCustomImpl.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordServiceImpl.java
Labels: implement

#144 main <- dev
  src/main/java/com/example/pomeserver/domain/record/controller/RecordController.java
  src/main/java/com/example/pomeserver/domain/record/repository/RecordRepositoryCustom.java
  src/main/java/com/example/pomeserver/domain/record/repository/RecordRepositoryCustomImpl.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordServiceImpl.java
Labels: deploy

#145 [feature/edit-DTO] Record 생성 시, 코멘트 글자수 제한(20자 -> 150자) 수정
  src/main/java/com/example/pomeserver/domain/record/dto/request/RecordCreateRequest.java
Labels: dtoEdit

#146 main <- develop
  src/main/java/com/example/pomeserver/domain/record/dto/request/RecordCreateRequest.java
Labels: deploy

#149 main <- dev
  src/main/java/com/example/pomeserver/domain/record/controller/RecordController.java
  src/main/java/com/example/pomeserver/domain/record/dto/paramResolver/param/RecordFilteringParam.java
  src/main/java/com/example/pomeserver/domain/record/dto/paramResolver/resolver/RecordFilteringArgumentResolver.java
  src/main/java/com/example/pomeserver/domain/record/repository/RecordRepository.java
  src/main/java/com/example/pomeserver/domain/record/repository/RecordRepositoryCustom.java
  src/main/java/com/example/pomeserver/domain/record/repository/RecordRepositoryCustomImpl.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordService.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordServiceImpl.java
  src/main/java/com/example/pomeserver/global/config/WebMvcConfig.java
  src/main/java/com/example/pomeserver/global/util/supplier/MyLongSupplier.java
Labels: deploy

#153 #152 회원 탈퇴 기능 구현
  src/main/java/com/example/pomeserver/domain/user/controller/UserController.java
  src/main/java/com/example/pomeserver/domain/user/entity/User.java
  src/main/java/com/example/pomeserver/domain/user/entity/vo/UserType.java
  src/main/java/com/example/pomeserver/domain/user/exception/UserExceptionList.java
  src/main/java/com/example/pomeserver/domain/user/exception/excute/UserNotAllowedException.java
  src/main/java/com/example/pomeserver/domain/user/service/UserService.java
  src/main/java/com/example/pomeserver/domain/user/service/UserServiceImpl.java
Labels: implement

#155 #154 유저로그아웃 기능 구현 및 로그아웃 시 리프레시 토큰 삭제
  src/main/java/com/example/pomeserver/domain/user/controller/UserController.java
  src/main/java/com/example/pomeserver/domain/user/service/UserService.java
  src/main/java/com/example/pomeserver/domain/user/service/UserServiceImpl.java
Labels: implement

#159 #45 회고탭 감정 두개로 필터링 구현 완
  src/main/java/com/example/pomeserver/domain/record/repository/RecordRepositoryCustomImpl.java
Labels: implement

#161 main <- dev
  src/main/java/com/example/pomeserver/domain/record/controller/RecordController.java
  src/main/java/com/example/pomeserver/domain/record/repository/RecordRepositoryCustomImpl.java
Labels: deploy

#164 #163 User,Friend 서비스 테스트 코드 작성 완료
  src/main/java/com/example/pomeserver/domain/user/dto/request/UserNicknameRequest.java
  src/main/java/com/example/pomeserver/domain/user/dto/request/UserSignInRequest.java
  src/main/java/com/example/pomeserver/domain/user/dto/request/UserSignUpRequest.java
  src/main/java/com/example/pomeserver/domain/user/service/UserServiceImpl.java
  src/test/java/com/example/pomeserver/domain/user/service/UserServiceTest.java
Labels: implement

#165 #45 나의 기록에 친구에게 감정남기기할때 이미 감정이 존재하는 경우 수정을하면 firstEmotion이 수정되는 버그 해결
  src/main/java/com/example/pomeserver/domain/record/dto/response/emotion/EmotionResponse.java
  src/main/java/com/example/pomeserver/domain/record/dto/response/record/RecordResponse.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordService.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordServiceImpl.java
Labels: implement

#166 main <- dev
  src/main/java/com/example/pomeserver/domain/goal/controller/GoalCategoryController.java
  src/main/java/com/example/pomeserver/domain/goal/service/GoalCategoryService.java
  src/main/java/com/example/pomeserver/domain/goal/service/GoalCategoryServiceImpl.java
  src/main/java/com/example/pomeserver/domain/record/dto/response/emotion/EmotionResponse.java
  src/main/java/com/example/pomeserver/domain/record/dto/response/record/RecordResponse.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordService.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordServiceImpl.java
  src/main/java/com/example/pomeserver/domain/user/dto/request/UserNicknameRequest.java
  src/main/java/com/example/pomeserver/domain/user/dto/request/UserSignInRequest.java
  src/main/java/com/example/pomeserver/domain/user/dto/request/UserSignUpRequest.java
  src/main/java/com/example/pomeserver/domain/user/service/UserServiceImpl.java
  src/test/java/com/example/pomeserver/domain/goal/service/GoalServiceImplTest.java
  src/test/java/com/example/pomeserver/domain/user/service/UserServiceTest.java
Labels: deploy

#167 #45 나의 기록 페이징 조회 --> 특정 유저의 기록 페이징 조회로 수정
  src/main/java/com/example/pomeserver/domain/record/controller/RecordController.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordService.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordServiceImpl.java
Labels: implement

#168 main <- dev
  src/main/java/com/example/pomeserver/domain/record/controller/RecordController.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordService.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordServiceImpl.java
Labels: deploy

#170 Feature/record service
  src/main/java/com/example/pomeserver/domain/record/controller/RecordController.java
  src/main/java/com/example/pomeserver/domain/record/entity/HideRecord.java
  src/main/java/com/example/pomeserver/domain/record/entity/Record.java
  src/main/java/com/example/pomeserver/domain/record/repository/HideRecordRepository.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordService.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordServiceImpl.java
  src/main/java/com/example/pomeserver/domain/user/entity/User.java
Labels: implement

#171 main <- dev
  src/main/java/com/example/pomeserver/domain/record/controller/RecordController.java
  src/main/java/com/example/pomeserver/domain/record/entity/HideRecord.java
  src/main/java/com/example/pomeserver/domain/record/entity/Record.java
  src/main/java/com/example/pomeserver/domain/record/repository/HideRecordRepository.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordService.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordServiceImpl.java
  src/main/java/com/example/pomeserver/domain/user/entity/User.java
Labels: deploy

#172 #45 특정 게시물 숨기기:친구 기록들 조회시 숨기기한 글은 보이지 않도록 적용
  src/main/java/com/example/pomeserver/domain/record/repository/HideRecordRepository.java
  src/main/java/com/example/pomeserver/domain/record/repository/RecordRepository.java
  src/main/java/com/example/pomeserver/domain/record/repository/emotion/EmotionRecordRepository.java
  src/main/java/com/example/pomeserver/domain/record/repository/emotion/EmotionRepository.java
  src/main/java/com/example/pomeserver/domain/record/repository/hide/HideRecordRepository.java
  src/main/java/com/example/pomeserver/domain/record/repository/hide/HideRecordRepositoryCustom.java
  src/main/java/com/example/pomeserver/domain/record/repository/hide/HideRecordRepositoryCustomImpl.java
  src/main/java/com/example/pomeserver/domain/record/repository/record/RecordRepository.java
  src/main/java/com/example/pomeserver/domain/record/repository/record/RecordRepositoryCustom.java
  src/main/java/com/example/pomeserver/domain/record/repository/record/RecordRepositoryCustomImpl.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordServiceImpl.java
Labels: implement

#173 main <- dev
  src/main/java/com/example/pomeserver/domain/record/repository/HideRecordRepository.java
  src/main/java/com/example/pomeserver/domain/record/repository/RecordRepository.java
  src/main/java/com/example/pomeserver/domain/record/repository/emotion/EmotionRecordRepository.java
  src/main/java/com/example/pomeserver/domain/record/repository/emotion/EmotionRepository.java
  src/main/java/com/example/pomeserver/domain/record/repository/hide/HideRecordRepository.java
  src/main/java/com/example/pomeserver/domain/record/repository/hide/HideRecordRepositoryCustom.java
  src/main/java/com/example/pomeserver/domain/record/repository/hide/HideRecordRepositoryCustomImpl.java
  src/main/java/com/example/pomeserver/domain/record/repository/record/RecordRepository.java
  src/main/java/com/example/pomeserver/domain/record/repository/record/RecordRepositoryCustom.java
  src/main/java/com/example/pomeserver/domain/record/repository/record/RecordRepositoryCustomImpl.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordServiceImpl.java
Labels: deploy

#174 #45 특정 게시물 숨기기:특정 유저의 기록을 조회할 시에도 적용
  src/main/java/com/example/pomeserver/domain/record/repository/record/RecordRepositoryCustom.java
  src/main/java/com/example/pomeserver/domain/record/repository/record/RecordRepositoryCustomImpl.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordServiceImpl.java
Labels: implement

#175 main <- dev
  src/main/java/com/example/pomeserver/domain/record/repository/record/RecordRepositoryCustom.java
  src/main/java/com/example/pomeserver/domain/record/repository/record/RecordRepositoryCustomImpl.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordServiceImpl.java
Labels: deploy

#178 Feature/marshmello service
  src/main/java/com/example/pomeserver/domain/marshmello/entity/Marshmello.java
  src/main/java/com/example/pomeserver/domain/marshmello/repository/MarshmelloRepository.java
  src/main/java/com/example/pomeserver/domain/marshmello/service/MarshmelloService.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordServiceImpl.java
  src/main/java/com/example/pomeserver/domain/user/entity/User.java
  src/main/java/com/example/pomeserver/domain/user/entity/vo/ActivityCount.java
  src/main/java/com/example/pomeserver/domain/user/service/UserServiceImpl.java
  src/main/java/com/example/pomeserver/global/event/Activity.java
  src/main/java/com/example/pomeserver/global/event/ActivityType.java
  src/main/java/com/example/pomeserver/global/event/events/AddEmotion.java
  src/main/java/com/example/pomeserver/global/event/events/ChangePositiveToNegative.java
  src/main/java/com/example/pomeserver/global/event/events/FinishRecord.java
  src/main/java/com/example/pomeserver/global/event/events/SuccessGoal.java
  src/main/java/com/example/pomeserver/global/event/handler/UserActivityEventHandler.java
  src/main/java/com/example/pomeserver/global/event/publisher/UserActivityEventPublisher.java
  src/main/java/com/example/pomeserver/global/event/publisher/UserActivityEventPublisherImpl.java
  src/test/java/com/example/pomeserver/domain/user/service/UserServiceTest.java
Labels: implement

#179 main <- dev
  src/main/java/com/example/pomeserver/domain/marshmello/entity/Marshmello.java
  src/main/java/com/example/pomeserver/domain/marshmello/repository/MarshmelloRepository.java
  src/main/java/com/example/pomeserver/domain/marshmello/service/MarshmelloService.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordServiceImpl.java
  src/main/java/com/example/pomeserver/domain/user/entity/User.java
  src/main/java/com/example/pomeserver/domain/user/entity/vo/ActivityCount.java
  src/main/java/com/example/pomeserver/domain/user/service/UserServiceImpl.java
  src/main/java/com/example/pomeserver/global/event/Activity.java
  src/main/java/com/example/pomeserver/global/event/ActivityType.java
  src/main/java/com/example/pomeserver/global/event/events/AddEmotion.java
  src/main/java/com/example/pomeserver/global/event/events/ChangePositiveToNegative.java
  src/main/java/com/example/pomeserver/global/event/events/FinishRecord.java
  src/main/java/com/example/pomeserver/global/event/events/SuccessGoal.java
  src/main/java/com/example/pomeserver/global/event/handler/UserActivityEventHandler.java
  src/main/java/com/example/pomeserver/global/event/publisher/UserActivityEventPublisher.java
  src/main/java/com/example/pomeserver/global/event/publisher/UserActivityEventPublisherImpl.java
  src/test/java/com/example/pomeserver/domain/user/service/UserServiceTest.java
Labels: deploy

#180 #176 MarshmelloService 안의 메서드들 구현 완
  src/main/java/com/example/pomeserver/domain/marshmello/exception/MarshmelloException.java
  src/main/java/com/example/pomeserver/domain/marshmello/exception/MarshmelloExceptionList.java
  src/main/java/com/example/pomeserver/domain/marshmello/exception/execute/MarshmelloNotFoundException.java
  src/main/java/com/example/pomeserver/domain/marshmello/service/MarshmelloService.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordServiceImpl.java
Labels: implement

#181 main <-dev
  src/main/java/com/example/pomeserver/domain/marshmello/exception/MarshmelloException.java
  src/main/java/com/example/pomeserver/domain/marshmello/exception/MarshmelloExceptionList.java
  src/main/java/com/example/pomeserver/domain/marshmello/exception/execute/MarshmelloNotFoundException.java
  src/main/java/com/example/pomeserver/domain/marshmello/service/MarshmelloService.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordServiceImpl.java
Labels: deploy

#182 #176 유저의 마시멜로 정보 불러오기 컨트롤러 완 + 기록의 감정 변화 마시멜로 게이지 부여 로직 추가
  src/main/java/com/example/pomeserver/domain/marshmello/controller/MarshmelloController.java
  src/main/java/com/example/pomeserver/domain/marshmello/dto/response/MarshmelloResponse.java
  src/main/java/com/example/pomeserver/domain/marshmello/service/MarshmelloService.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordServiceImpl.java
Labels: implement

#183 main <- dev
  src/main/java/com/example/pomeserver/domain/marshmello/controller/MarshmelloController.java
  src/main/java/com/example/pomeserver/domain/marshmello/dto/response/MarshmelloResponse.java
  src/main/java/com/example/pomeserver/domain/marshmello/service/MarshmelloService.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordServiceImpl.java
Labels: deploy

#185 [hotfix/goal-service] 목표 종료 시, 목표 성공 여부 갱신
  src/main/java/com/example/pomeserver/domain/goal/entity/Goal.java
  src/main/java/com/example/pomeserver/domain/goal/service/GoalServiceImpl.java
Labels: hotfix

#186 main <- develop
  LICENSE
  src/main/java/com/example/pomeserver/domain/goal/entity/Goal.java
  src/main/java/com/example/pomeserver/domain/goal/service/GoalServiceImpl.java
Labels: deploy

#187 #176 목표 성공 마시멜로 이벤트 코드 삽입 완
  src/main/java/com/example/pomeserver/domain/goal/service/GoalServiceImpl.java
  src/main/java/com/example/pomeserver/domain/marshmello/controller/MarshmelloController.java
Labels: implement

#188 main <- dev
  src/main/java/com/example/pomeserver/domain/goal/service/GoalServiceImpl.java
  src/main/java/com/example/pomeserver/domain/marshmello/controller/MarshmelloController.java
Labels: deploy

#189 #174 마시멜로- UserActivity관련 잘못된 count증가 메서드 수정
  src/main/java/com/example/pomeserver/domain/record/service/RecordServiceImpl.java
  src/main/java/com/example/pomeserver/global/event/handler/UserActivityEventHandler.java
Labels: implement

#190 main <- dev
  src/main/java/com/example/pomeserver/domain/record/service/RecordServiceImpl.java
  src/main/java/com/example/pomeserver/global/event/handler/UserActivityEventHandler.java
Labels: deploy

#191 Feature/marshmello service
  src/main/java/com/example/pomeserver/domain/record/entity/Record.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordServiceImpl.java
Labels: hotfix

#192 main <- dev
  src/main/java/com/example/pomeserver/domain/record/entity/Record.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordServiceImpl.java
Labels: deploy

#193 #176 안드로이드용 리스트로 마시멜로 응답 api 추가
  src/main/java/com/example/pomeserver/domain/marshmello/controller/MarshmelloController.java
  src/main/java/com/example/pomeserver/domain/marshmello/dto/response/MarshmelloSmallResponse.java
  src/main/java/com/example/pomeserver/domain/marshmello/service/MarshmelloService.java
Labels: implement

#194 main <- dev
  src/main/java/com/example/pomeserver/domain/marshmello/controller/MarshmelloController.java
  src/main/java/com/example/pomeserver/domain/marshmello/dto/response/MarshmelloSmallResponse.java
  src/main/java/com/example/pomeserver/domain/marshmello/service/MarshmelloService.java
Labels: deploy

#195 #40 기획에 따른 유저 닉네임 글자수 제한 기능
  src/main/java/com/example/pomeserver/domain/user/dto/request/UserNicknameRequest.java
Labels: hotfix

#197 Feature/marshmello service
  src/main/java/com/example/pomeserver/domain/record/controller/RecordController.java
  src/main/java/com/example/pomeserver/domain/record/dto/paramResolver/param/RecordFilteringParam.java
  src/main/java/com/example/pomeserver/domain/record/repository/record/RecordRepositoryCustomImpl.java
Labels: implement

#198 main <- dev
  README.md
  src/main/java/com/example/pomeserver/domain/record/controller/RecordController.java
  src/main/java/com/example/pomeserver/domain/record/dto/paramResolver/param/RecordFilteringParam.java
  src/main/java/com/example/pomeserver/domain/record/repository/record/RecordRepositoryCustomImpl.java
  src/main/java/com/example/pomeserver/domain/user/dto/request/UserNicknameRequest.java
Labels: deploy

#199 [hotfix/goal-service] 목표이름 중복 허용에 따른 목표 카테고리 테이블 삭제
  src/main/java/com/example/pomeserver/domain/goal/controller/GoalCategoryController.java
  src/main/java/com/example/pomeserver/domain/goal/controller/GoalController.java
  src/main/java/com/example/pomeserver/domain/goal/dto/assembler/GoalAssembler.java
  src/main/java/com/example/pomeserver/domain/goal/dto/assembler/GoalCategoryAssembler.java
  src/main/java/com/example/pomeserver/domain/goal/dto/request/GoalCategoryCreateRequest.java
  src/main/java/com/example/pomeserver/domain/goal/dto/request/GoalUpdateRequest.java
  src/main/java/com/example/pomeserver/domain/goal/dto/response/GoalCategoryResponse.java
  src/main/java/com/example/pomeserver/domain/goal/dto/response/GoalResponse.java
  src/main/java/com/example/pomeserver/domain/goal/entity/Goal.java
  src/main/java/com/example/pomeserver/domain/goal/entity/GoalCategory.java
  src/main/java/com/example/pomeserver/domain/goal/repository/GoalCategoryRepository.java
  src/main/java/com/example/pomeserver/domain/goal/repository/GoalRepository.java
  src/main/java/com/example/pomeserver/domain/goal/service/GoalCategoryService.java
  src/main/java/com/example/pomeserver/domain/goal/service/GoalCategoryServiceImpl.java
  src/main/java/com/example/pomeserver/domain/goal/service/GoalService.java
  src/main/java/com/example/pomeserver/domain/goal/service/GoalServiceImpl.java
  src/main/java/com/example/pomeserver/domain/user/entity/User.java
  src/test/java/com/example/pomeserver/domain/goal/service/GoalServiceImplTest.java
Labels: hotfix

#200 main <- develop
  src/main/java/com/example/pomeserver/domain/goal/controller/GoalCategoryController.java
  src/main/java/com/example/pomeserver/domain/goal/controller/GoalController.java
  src/main/java/com/example/pomeserver/domain/goal/dto/assembler/GoalAssembler.java
  src/main/java/com/example/pomeserver/domain/goal/dto/assembler/GoalCategoryAssembler.java
  src/main/java/com/example/pomeserver/domain/goal/dto/request/GoalCategoryCreateRequest.java
  src/main/java/com/example/pomeserver/domain/goal/dto/request/GoalUpdateRequest.java
  src/main/java/com/example/pomeserver/domain/goal/dto/response/GoalCategoryResponse.java
  src/main/java/com/example/pomeserver/domain/goal/dto/response/GoalResponse.java
  src/main/java/com/example/pomeserver/domain/goal/entity/Goal.java
  src/main/java/com/example/pomeserver/domain/goal/entity/GoalCategory.java
  src/main/java/com/example/pomeserver/domain/goal/repository/GoalCategoryRepository.java
  src/main/java/com/example/pomeserver/domain/goal/repository/GoalRepository.java
  src/main/java/com/example/pomeserver/domain/goal/service/GoalCategoryService.java
  src/main/java/com/example/pomeserver/domain/goal/service/GoalCategoryServiceImpl.java
  src/main/java/com/example/pomeserver/domain/goal/service/GoalService.java
  src/main/java/com/example/pomeserver/domain/goal/service/GoalServiceImpl.java
  src/main/java/com/example/pomeserver/domain/user/entity/User.java
  src/test/java/com/example/pomeserver/domain/goal/service/GoalServiceImplTest.java
Labels: deploy

#201 #176 #45 QA반영: 1.공감말랑<- 수정한 감정에는 공감말랑 카운트되지 않도록/ 2.자신의 기록에 자신이 감정을 남길…
  src/main/java/com/example/pomeserver/domain/record/controller/RecordController.java
  src/main/java/com/example/pomeserver/domain/record/exception/emotion/EmotionExceptionList.java
  src/main/java/com/example/pomeserver/domain/record/exception/emotion/excute/LeaveEmotionToMyRecordException.java
  src/main/java/com/example/pomeserver/domain/record/repository/record/RecordRepositoryCustomImpl.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordServiceImpl.java
Labels: implement, dtoEdit

#202 main <- dev
  README.md
  src/main/java/com/example/pomeserver/domain/record/controller/RecordController.java
  src/main/java/com/example/pomeserver/domain/record/exception/emotion/EmotionExceptionList.java
  src/main/java/com/example/pomeserver/domain/record/exception/emotion/excute/LeaveEmotionToMyRecordException.java
  src/main/java/com/example/pomeserver/domain/record/repository/record/RecordRepositoryCustomImpl.java
  src/main/java/com/example/pomeserver/domain/record/service/RecordServiceImpl.java
Labels: deploy

#203 완료된 목표에 대해서만 중복 허용
  src/main/java/com/example/pomeserver/domain/goal/repository/GoalRepository.java
  src/main/java/com/example/pomeserver/domain/goal/service/GoalServiceImpl.java
  src/main/resources/application.yml
Labels: hotfix
